import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ─── Menu Items Seed Data ──────────────────────────────────────
const menuItems = [
  // ── VEG STARTERS ──────────────────────────────────────────
  {
    name: "Paneer Tikka",
    category: "Veg Starters",
    price: 280,
    description: "Marinated cottage cheese cubes grilled in tandoor with bell peppers & onions. Smoky, juicy, legendary.",
    imageUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400",
    tags: ["veg", "spicy", "bestseller", "tandoor", "gluten-free"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: true,
    calories: 320,
    prepTime: 15,
    popularScore: 0.92,
  },
  {
    name: "Hara Bhara Kabab",
    category: "Veg Starters",
    price: 220,
    description: "Spinach & pea patties with herbs, lightly pan-fried. A wholesome guilt-free indulgence.",
    imageUrl: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400",
    tags: ["veg", "light", "healthy", "quick-serve"],
    allergens: ["gluten"],
    isVeg: true,
    isSpicy: false,
    calories: 180,
    prepTime: 10,
    popularScore: 0.74,
  },
  {
    name: "Veg Seekh Kebab",
    category: "Veg Starters",
    price: 240,
    description: "Spiced mixed vegetable & paneer kebabs on skewers with smoky char. Perfect with mint chutney.",
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400",
    tags: ["veg", "spicy", "tandoor"],
    allergens: ["dairy", "gluten"],
    isVeg: true,
    isSpicy: true,
    calories: 260,
    prepTime: 15,
    popularScore: 0.71,
  },
  {
    name: "Stuffed Mushroom",
    category: "Veg Starters",
    price: 260,
    description: "Button mushrooms stuffed with spiced cheese & herbs, baked golden. Rich umami in every bite.",
    imageUrl: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400",
    tags: ["veg", "light", "chef-special"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 210,
    prepTime: 12,
    popularScore: 0.68,
  },
  {
    name: "Crispy Corn",
    category: "Veg Starters",
    price: 180,
    description: "Corn kernels tossed with spices in a crispy coating. Addictively crunchy, can't stop at one.",
    imageUrl: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400",
    tags: ["veg", "light", "quick-serve", "bestseller"],
    allergens: ["gluten"],
    isVeg: true,
    isSpicy: true,
    calories: 220,
    prepTime: 8,
    popularScore: 0.83,
  },
  {
    name: "Aloo Tikki Chaat",
    category: "Veg Starters",
    price: 160,
    description: "Crispy potato patties topped with chutneys, yogurt & sev. Street food magic, plated elegantly.",
    imageUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400",
    tags: ["veg", "spicy", "street-food"],
    allergens: ["dairy", "gluten"],
    isVeg: true,
    isSpicy: true,
    calories: 280,
    prepTime: 10,
    popularScore: 0.77,
  },

  // ── NON-VEG STARTERS ──────────────────────────────────────
  {
    name: "Chilli Chicken Bites",
    category: "Non-Veg Starters",
    price: 320,
    description: "Crispy boneless chicken tossed in a fiery Indo-Chinese chilli sauce. Bold, hot, unforgettable.",
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400",
    tags: ["non-veg", "spicy", "bestseller", "crispy"],
    allergens: ["gluten", "soy"],
    isVeg: false,
    isSpicy: true,
    calories: 380,
    prepTime: 15,
    popularScore: 0.95,
  },
  {
    name: "Tandoori Chicken Half",
    category: "Non-Veg Starters",
    price: 380,
    description: "Half chicken marinated overnight in yogurt & spices, roasted in clay oven. A classic done right.",
    imageUrl: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400",
    tags: ["non-veg", "spicy", "tandoor", "bestseller"],
    allergens: ["dairy"],
    isVeg: false,
    isSpicy: true,
    calories: 450,
    prepTime: 20,
    popularScore: 0.91,
  },
  {
    name: "Prawn Pepper Fry",
    category: "Non-Veg Starters",
    price: 420,
    description: "Jumbo prawns sautéed with cracked pepper, curry leaves & coconut — South Indian coastal style.",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
    tags: ["non-veg", "spicy", "seafood", "chef-special"],
    allergens: ["shellfish"],
    isVeg: false,
    isSpicy: true,
    calories: 310,
    prepTime: 18,
    popularScore: 0.88,
  },
  {
    name: "Fish Tikka",
    category: "Non-Veg Starters",
    price: 360,
    description: "Firm white fish fillets in a light marinade of lemon & tandoori spices. Smoky and delicate.",
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400",
    tags: ["non-veg", "light", "seafood", "tandoor"],
    allergens: ["fish"],
    isVeg: false,
    isSpicy: false,
    calories: 280,
    prepTime: 15,
    popularScore: 0.82,
  },
  {
    name: "Chicken Seekh Kebab",
    category: "Non-Veg Starters",
    price: 340,
    description: "Minced chicken with ginger, garlic & spices on skewers, grilled to juicy perfection.",
    imageUrl: "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=400",
    tags: ["non-veg", "spicy", "tandoor"],
    allergens: [],
    isVeg: false,
    isSpicy: true,
    calories: 360,
    prepTime: 15,
    popularScore: 0.79,
  },

  // ── MAINS (VEG) ────────────────────────────────────────────
  {
    name: "Paneer Butter Masala",
    category: "Mains (Veg)",
    price: 320,
    description: "Velvety tomato-cream gravy with paneer cubes. Rich, slightly sweet, and absolutely comforting.",
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    tags: ["veg", "filling", "bestseller", "mild"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 520,
    prepTime: 15,
    popularScore: 0.96,
  },
  {
    name: "Dal Makhani",
    category: "Mains (Veg)",
    price: 280,
    description: "Slow-cooked black lentils with butter & cream, simmered for 12 hours. A Punjab classic.",
    imageUrl: "https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=400",
    tags: ["veg", "filling", "bestseller", "mild"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 480,
    prepTime: 10,
    popularScore: 0.94,
  },
  {
    name: "Palak Paneer",
    category: "Mains (Veg)",
    price: 300,
    description: "Fresh spinach puree with cottage cheese chunks. Healthy, flavourful, vibrant green goodness.",
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400",
    tags: ["veg", "healthy", "filling"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 420,
    prepTime: 12,
    popularScore: 0.87,
  },
  {
    name: "Kadai Mushroom",
    category: "Mains (Veg)",
    price: 290,
    description: "Button mushrooms cooked with bell peppers in a robust kadai masala. Earthy and aromatic.",
    imageUrl: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400",
    tags: ["veg", "spicy", "filling"],
    allergens: [],
    isVeg: true,
    isSpicy: true,
    calories: 350,
    prepTime: 12,
    popularScore: 0.72,
  },
  {
    name: "Chana Masala",
    category: "Mains (Veg)",
    price: 260,
    description: "Protein-rich chickpeas in a tangy, spicy tomato gravy. Wholesome and full of fibre.",
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400",
    tags: ["veg", "spicy", "healthy", "filling"],
    allergens: [],
    isVeg: true,
    isSpicy: true,
    calories: 380,
    prepTime: 10,
    popularScore: 0.80,
  },
  {
    name: "Shahi Paneer",
    category: "Mains (Veg)",
    price: 340,
    description: "Royal paneer in cashew-cream gravy with subtle saffron notes. Luxurious and indulgent.",
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    tags: ["veg", "filling", "premium", "mild"],
    allergens: ["dairy", "nuts"],
    isVeg: true,
    isSpicy: false,
    calories: 560,
    prepTime: 15,
    popularScore: 0.85,
  },

  // ── MAINS (NON-VEG) ───────────────────────────────────────
  {
    name: "Butter Chicken",
    category: "Mains (Non-Veg)",
    price: 380,
    description: "Tender chicken in silky tomato-cream sauce. The iconic dish that defines Indian dining worldwide.",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400",
    tags: ["non-veg", "filling", "bestseller", "mild"],
    allergens: ["dairy"],
    isVeg: false,
    isSpicy: false,
    calories: 580,
    prepTime: 15,
    popularScore: 0.98,
  },
  {
    name: "Mutton Rogan Josh",
    category: "Mains (Non-Veg)",
    price: 460,
    description: "Slow-braised Kashmiri mutton in aromatic whole spices. Bold, fragrant, melt-off-the-bone.",
    imageUrl: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400",
    tags: ["non-veg", "spicy", "filling", "chef-special"],
    allergens: [],
    isVeg: false,
    isSpicy: true,
    calories: 620,
    prepTime: 20,
    popularScore: 0.90,
  },
  {
    name: "Prawn Curry",
    category: "Mains (Non-Veg)",
    price: 480,
    description: "Plump prawns in a coconut-based Goan curry. Tangy, spiced, with a tropical finish.",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
    tags: ["non-veg", "spicy", "seafood", "chef-special"],
    allergens: ["shellfish", "coconut"],
    isVeg: false,
    isSpicy: true,
    calories: 420,
    prepTime: 18,
    popularScore: 0.86,
  },
  {
    name: "Chicken Biryani",
    category: "Mains (Non-Veg)",
    price: 360,
    description: "Basmati rice layered with spiced chicken, saffron & fried onions. Aromatic perfection.",
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
    tags: ["non-veg", "filling", "bestseller", "biryani"],
    allergens: ["dairy"],
    isVeg: false,
    isSpicy: true,
    calories: 680,
    prepTime: 20,
    popularScore: 0.97,
  },
  {
    name: "Kadai Chicken",
    category: "Mains (Non-Veg)",
    price: 360,
    description: "Chicken cooked in a wok with tomatoes, capsicum & whole spices. Rustic, hearty, bold.",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400",
    tags: ["non-veg", "spicy", "filling"],
    allergens: [],
    isVeg: false,
    isSpicy: true,
    calories: 500,
    prepTime: 18,
    popularScore: 0.84,
  },

  // ── BREADS & RICE ─────────────────────────────────────────
  {
    name: "Garlic Naan",
    category: "Breads & Rice",
    price: 80,
    description: "Freshly baked naan brushed with garlic butter & fresh coriander. Pillowy perfection.",
    imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400",
    tags: ["veg", "bread", "bestseller", "quick-serve"],
    allergens: ["gluten", "dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 220,
    prepTime: 8,
    popularScore: 0.95,
  },
  {
    name: "Butter Roti",
    category: "Breads & Rice",
    price: 50,
    description: "Whole wheat flatbread topped with butter. Simple, wholesome, and always satisfying.",
    imageUrl: "https://images.unsplash.com/photo-1548340748-6d2b7d7da280?w=400",
    tags: ["veg", "bread", "light", "quick-serve"],
    allergens: ["gluten", "dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 130,
    prepTime: 5,
    popularScore: 0.88,
  },
  {
    name: "Peshwari Naan",
    category: "Breads & Rice",
    price: 120,
    description: "Stuffed naan with sweetened nuts & coconut filling. Indulgent dessert-bread crossover.",
    imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400",
    tags: ["veg", "bread", "sweet", "premium"],
    allergens: ["gluten", "dairy", "nuts"],
    isVeg: true,
    isSpicy: false,
    calories: 290,
    prepTime: 10,
    popularScore: 0.65,
  },
  {
    name: "Jeera Rice",
    category: "Breads & Rice",
    price: 140,
    description: "Basmati rice tempered with cumin & ghee. Light, fragrant, and the perfect curry companion.",
    imageUrl: "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400",
    tags: ["veg", "rice", "light", "quick-serve"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 240,
    prepTime: 8,
    popularScore: 0.84,
  },
  {
    name: "Veg Fried Rice",
    category: "Breads & Rice",
    price: 200,
    description: "Wok-tossed rice with vegetables in a smoky, umami-rich sauce. Indo-Chinese comfort.",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400",
    tags: ["veg", "rice", "filling"],
    allergens: ["soy", "gluten"],
    isVeg: true,
    isSpicy: false,
    calories: 380,
    prepTime: 12,
    popularScore: 0.76,
  },

  // ── DESSERTS ──────────────────────────────────────────────
  {
    name: "Gulab Jamun",
    category: "Desserts",
    price: 120,
    description: "Soft khoya dumplings soaked in rose-saffron sugar syrup. Warm, indulgent, timeless.",
    imageUrl: "https://images.unsplash.com/photo-1541599468348-e96984315921?w=400",
    tags: ["veg", "sweet", "bestseller", "quick-serve"],
    allergens: ["dairy", "gluten"],
    isVeg: true,
    isSpicy: false,
    calories: 320,
    prepTime: 5,
    popularScore: 0.93,
  },
  {
    name: "Kulfi",
    category: "Desserts",
    price: 140,
    description: "Dense, creamy Indian ice cream in pistachio-cardamom flavour. Slow-frozen tradition.",
    imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400",
    tags: ["veg", "sweet", "cold", "chef-special"],
    allergens: ["dairy", "nuts"],
    isVeg: true,
    isSpicy: false,
    calories: 260,
    prepTime: 3,
    popularScore: 0.89,
  },
  {
    name: "Chocolate Lava Cake",
    category: "Desserts",
    price: 200,
    description: "Warm dark chocolate cake with molten centre, served with vanilla ice cream. Pure luxury.",
    imageUrl: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400",
    tags: ["veg", "sweet", "chocolate", "premium", "chef-special"],
    allergens: ["gluten", "dairy", "eggs"],
    isVeg: true,
    isSpicy: false,
    calories: 480,
    prepTime: 10,
    popularScore: 0.91,
  },
  {
    name: "Rasmalai",
    category: "Desserts",
    price: 160,
    description: "Spongy paneer dumplings in chilled saffron-infused milk. Delicate, fragrant, heavenly.",
    imageUrl: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=400",
    tags: ["veg", "sweet", "light", "cold"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 280,
    prepTime: 3,
    popularScore: 0.85,
  },
  {
    name: "Gajar Halwa",
    category: "Desserts",
    price: 140,
    description: "Slow-cooked grated carrot in ghee with khoya & cardamom. Winter warmth in a bowl.",
    imageUrl: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400",
    tags: ["veg", "sweet", "traditional"],
    allergens: ["dairy", "nuts"],
    isVeg: true,
    isSpicy: false,
    calories: 360,
    prepTime: 5,
    popularScore: 0.73,
  },

  // ── BEVERAGES (HOT) ───────────────────────────────────────
  {
    name: "Masala Chai",
    category: "Beverages (Hot)",
    price: 80,
    description: "Spiced Indian tea with ginger, cardamom & mint. The sip that starts every great conversation.",
    imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400",
    tags: ["veg", "hot", "bestseller", "quick-serve"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 80,
    prepTime: 5,
    popularScore: 0.90,
  },
  {
    name: "Filter Coffee",
    category: "Beverages (Hot)",
    price: 90,
    description: "South Indian decoction with frothy milk, served in a traditional tumbler & davara.",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
    tags: ["veg", "hot", "south-indian", "bestseller"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 70,
    prepTime: 5,
    popularScore: 0.87,
  },
  {
    name: "Kashmiri Kahwa",
    category: "Beverages (Hot)",
    price: 120,
    description: "Green tea with saffron, cinnamon & almonds. Exotic, warming, and utterly sophisticated.",
    imageUrl: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400",
    tags: ["veg", "hot", "premium", "chef-special"],
    allergens: ["nuts"],
    isVeg: true,
    isSpicy: false,
    calories: 40,
    prepTime: 6,
    popularScore: 0.78,
  },
  {
    name: "Hot Chocolate",
    category: "Beverages (Hot)",
    price: 160,
    description: "Rich Belgian chocolate melted into velvety milk with a touch of sea salt. Pure decadence.",
    imageUrl: "https://images.unsplash.com/photo-1517578239113-b03992dcdd25?w=400",
    tags: ["veg", "hot", "sweet", "chocolate"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 220,
    prepTime: 5,
    popularScore: 0.82,
  },

  // ── BEVERAGES (COLD) ──────────────────────────────────────
  {
    name: "Mango Lassi",
    category: "Beverages (Cold)",
    price: 140,
    description: "Thick Alphonso mango blended with creamy yogurt. Summer in a glass, all year round.",
    imageUrl: "https://images.unsplash.com/photo-1571950006418-df6bc1280e49?w=400",
    tags: ["veg", "cold", "sweet", "bestseller", "refreshing"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 240,
    prepTime: 3,
    popularScore: 0.94,
  },
  {
    name: "Virgin Mojito",
    category: "Beverages (Cold)",
    price: 160,
    description: "Fresh mint, lime & soda water with a hint of sugar. Crisp, refreshing, zero guilt.",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400",
    tags: ["veg", "cold", "refreshing", "light", "quick-serve"],
    allergens: [],
    isVeg: true,
    isSpicy: false,
    calories: 90,
    prepTime: 3,
    popularScore: 0.89,
  },
  {
    name: "Rose Lemonade",
    category: "Beverages (Cold)",
    price: 140,
    description: "Fresh lemon juice with rose syrup & sparkling water. Floral, tangy, and incredibly pink.",
    imageUrl: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400",
    tags: ["veg", "cold", "sweet", "refreshing"],
    allergens: [],
    isVeg: true,
    isSpicy: false,
    calories: 110,
    prepTime: 3,
    popularScore: 0.81,
  },
  {
    name: "Watermelon Mint Cooler",
    category: "Beverages (Cold)",
    price: 150,
    description: "Fresh watermelon juice blended with mint & a pinch of chaat masala. Summer soul restorer.",
    imageUrl: "https://images.unsplash.com/photo-1440491927789-e39bd96d5f2b?w=400",
    tags: ["veg", "cold", "light", "healthy", "refreshing"],
    allergens: [],
    isVeg: true,
    isSpicy: false,
    calories: 80,
    prepTime: 4,
    popularScore: 0.76,
  },
  {
    name: "Thandai Shake",
    category: "Beverages (Cold)",
    price: 180,
    description: "Traditional spiced milk shake with rose petals & nuts. Festive, rich, uniquely Indian.",
    imageUrl: "https://images.unsplash.com/photo-1571950006418-df6bc1280e49?w=400",
    tags: ["veg", "cold", "sweet", "premium"],
    allergens: ["dairy", "nuts"],
    isVeg: true,
    isSpicy: false,
    calories: 290,
    prepTime: 5,
    popularScore: 0.71,
  },

  // ── COMBOS & DEALS ────────────────────────────────────────
  {
    name: "Party Platter (Veg)",
    category: "Combos & Deals",
    price: 680,
    description: "Paneer Tikka + Hara Bhara Kabab + Crispy Corn + Mint Chutney. Feeds 2-3, guaranteed crowd-pleaser.",
    imageUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400",
    tags: ["veg", "shareable", "combo", "bestseller"],
    allergens: ["dairy", "gluten"],
    isVeg: true,
    isSpicy: false,
    calories: 900,
    prepTime: 20,
    popularScore: 0.93,
  },
  {
    name: "Non-Veg Party Platter",
    category: "Combos & Deals",
    price: 880,
    description: "Tandoori Chicken + Chilli Bites + Fish Tikka + Seekh Kebab. The ultimate meat lover's spread.",
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400",
    tags: ["non-veg", "shareable", "combo", "bestseller"],
    allergens: ["gluten", "dairy", "fish"],
    isVeg: false,
    isSpicy: true,
    calories: 1200,
    prepTime: 25,
    popularScore: 0.96,
  },
  {
    name: "Couple's Delight",
    category: "Combos & Deals",
    price: 760,
    description: "Butter Chicken + Dal Makhani + 2 Garlic Naans + 2 Mango Lassis. Date night sorted.",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400",
    tags: ["non-veg", "combo", "filling", "shareable"],
    allergens: ["dairy", "gluten"],
    isVeg: false,
    isSpicy: false,
    calories: 1500,
    prepTime: 20,
    popularScore: 0.91,
  },
  {
    name: "Meal Deal — Veg",
    category: "Combos & Deals",
    price: 440,
    description: "Any Veg Main + Jeera Rice or 2 Rotis + Mango Lassi. Complete lunch sorted at one price.",
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    tags: ["veg", "combo", "filling", "lunch"],
    allergens: ["dairy", "gluten"],
    isVeg: true,
    isSpicy: false,
    calories: 1100,
    prepTime: 15,
    popularScore: 0.88,
  },
  {
    name: "Dessert Duo",
    category: "Combos & Deals",
    price: 220,
    description: "Gulab Jamun + Kulfi — the perfect sweet ending for two. Tradition meets indulgence.",
    imageUrl: "https://images.unsplash.com/photo-1541599468348-e96984315921?w=400",
    tags: ["veg", "combo", "sweet", "shareable"],
    allergens: ["dairy", "gluten", "nuts"],
    isVeg: true,
    isSpicy: false,
    calories: 580,
    prepTime: 5,
    popularScore: 0.85,
  },

  // ── ADDITIONAL ITEMS (for complementary matching) ─────────
  {
    name: "Mint Chutney",
    category: "Veg Starters",
    price: 40,
    description: "Fresh coriander-mint dip with green chillies. The green hero that elevates everything.",
    imageUrl: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400",
    tags: ["veg", "light", "condiment", "quick-serve"],
    allergens: [],
    isVeg: true,
    isSpicy: true,
    calories: 20,
    prepTime: 2,
    popularScore: 0.88,
  },
  {
    name: "Masala Naan",
    category: "Breads & Rice",
    price: 100,
    description: "Naan stuffed with spiced onion & herbs, baked in tandoor till golden. Meal in itself.",
    imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400",
    tags: ["veg", "bread", "spicy", "filling"],
    allergens: ["gluten", "dairy"],
    isVeg: true,
    isSpicy: true,
    calories: 260,
    prepTime: 10,
    popularScore: 0.78,
  },
  {
    name: "Plain Lassi",
    category: "Beverages (Cold)",
    price: 100,
    description: "Chilled salted yogurt drink with a hint of cumin. Classic cooling companion for spicy mains.",
    imageUrl: "https://images.unsplash.com/photo-1571950006418-df6bc1280e49?w=400",
    tags: ["veg", "cold", "light", "refreshing"],
    allergens: ["dairy"],
    isVeg: true,
    isSpicy: false,
    calories: 120,
    prepTime: 3,
    popularScore: 0.80,
  },
];

// ─── Complement Pairs ─────────────────────────────────────────
// We'll set these up after inserting menu items
const complementPairs: [string, string][] = [
  ["Paneer Tikka", "Mint Chutney"],
  ["Paneer Tikka", "Masala Naan"],
  ["Chilli Chicken Bites", "Mint Chutney"],
  ["Chilli Chicken Bites", "Virgin Mojito"],
  ["Butter Chicken", "Garlic Naan"],
  ["Butter Chicken", "Jeera Rice"],
  ["Butter Chicken", "Mango Lassi"],
  ["Dal Makhani", "Garlic Naan"],
  ["Dal Makhani", "Butter Roti"],
  ["Chicken Biryani", "Plain Lassi"],
  ["Chicken Biryani", "Raita"],
  ["Mutton Rogan Josh", "Garlic Naan"],
  ["Mutton Rogan Josh", "Jeera Rice"],
  ["Paneer Butter Masala", "Garlic Naan"],
  ["Paneer Butter Masala", "Mango Lassi"],
  ["Hara Bhara Kabab", "Mint Chutney"],
  ["Fish Tikka", "Rose Lemonade"],
  ["Prawn Pepper Fry", "Jeera Rice"],
  ["Gulab Jamun", "Filter Coffee"],
  ["Chocolate Lava Cake", "Hot Chocolate"],
];

async function main() {
  console.log("🌱 Starting database seed...");

  // Clear existing data (order matters for FK constraints)
  await prisma.complement.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.message.deleteMany();
  await prisma.session.deleteMany();
  await prisma.menuItem.deleteMany();

  console.log("✓ Cleared existing data");

  // Insert menu items
  const createdItems: Record<string, string> = {}; // name -> id

  for (const item of menuItems) {
    const created = await prisma.menuItem.create({
      data: {
        name: item.name,
        category: item.category,
        price: item.price,
        description: item.description,
        imageUrl: item.imageUrl,
        tags: item.tags,
        allergens: item.allergens,
        available: true,
        popularScore: item.popularScore,
        isVeg: item.isVeg,
        isSpicy: item.isSpicy,
        calories: item.calories,
        prepTime: item.prepTime,
      },
    });
    createdItems[item.name] = created.id;
    process.stdout.write(".");
  }

  console.log(`\n✓ Seeded ${menuItems.length} menu items`);

  // Insert complementary pairs (bidirectional)
  let complementCount = 0;
  for (const [fromName, toName] of complementPairs) {
    const fromId = createdItems[fromName];
    const toId = createdItems[toName];

    if (!fromId || !toId) {
      console.warn(`  ⚠ Skipping complement: "${fromName}" <-> "${toName}" (item not found)`);
      continue;
    }

    // Insert both directions
    await prisma.complement.createMany({
      data: [
        { fromId, toId },
        { fromId: toId, toId: fromId },
      ],
      skipDuplicates: true,
    });
    complementCount++;
  }

  console.log(`✓ Seeded ${complementCount * 2} complement relationships`);
  console.log("\n🎉 Database seeded successfully!");
  console.log(`   Menu items: ${menuItems.length}`);
  console.log(`   Categories: ${[...new Set(menuItems.map((i) => i.category))].length}`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
